import * as m from "$shared/i18n/messages";
export const fields = {
  "general.pages": {
    section: "general",
    label: m.general_startup_pages,
    description: m.general_startup_pages_help,
    initial: "",
  },
  "languages.translate": {
    section: "languages",
    label: m.language_translate,
    description: m.language_translate_help,
    initial: true,
  },
  "search.open-new": {
    section: "search",
    label: m.search_open_new,
    description: m.search_open_new_help,
    initial: false,
  },
  "privacy.cleanup": {
    section: "privacy",
    label: m.privacy_on_exit,
    description: m.privacy_on_exit_help,
    initial: false,
  },
  "developer.menu": {
    section: "developer",
    label: m.developer_menu,
    description: m.developer_menu_help,
    initial: true,
  },
  "developer.confirm": {
    section: "developer",
    label: m.developer_confirm,
    description: m.developer_confirm_help,
    initial: true,
  },
  "developer.local": {
    section: "developer",
    label: m.developer_local,
    description: m.developer_local_help,
    initial: false,
  },
  "updates.automatic": {
    section: "about",
    label: m.updates_automatic,
    description: m.updates_automatic_help,
    initial: true,
  },
  "updates.check": {
    section: "about",
    label: m.updates_check,
    description: m.updates_note,
    initial: "",
  },
  "privacy.popups": {
    section: "privacy",
    label: m.permission_popups,
    description: m.privacy_popups_help,
    initial: "Block",
    options: [
      { value: "Ask", label: m.permission_ask },
      { value: "Allow", label: m.permission_allow },
      { value: "Block", label: m.permission_block },
    ],
  },
  "privacy.clipboard": {
    section: "privacy",
    label: m.permission_clipboard,
    description: m.privacy_clipboard_help,
    initial: "Ask",
    options: [
      { value: "Ask", label: m.permission_ask },
      { value: "Allow", label: m.permission_allow },
      { value: "Block", label: m.permission_block },
    ],
  },
  "privacy.automatic-downloads": {
    section: "privacy",
    label: m.permission_automatic_downloads,
    description: m.privacy_downloads_help,
    initial: "Ask",
    options: [
      { value: "Ask", label: m.permission_ask },
      { value: "Allow", label: m.permission_allow },
      { value: "Block", label: m.permission_block },
    ],
  },
  "privacy.sound": {
    section: "privacy",
    label: m.permission_sound,
    description: m.privacy_sound_help,
    initial: "Allow",
    options: [
      { value: "Ask", label: m.permission_ask },
      { value: "Allow", label: m.permission_allow },
      { value: "Block", label: m.permission_block },
    ],
  },
  "updates.channel": {
    section: "about",
    label: m.updates_channel,
    description: m.updates_channel_help,
    initial: "stable",
    options: [
      { value: "stable", label: m.updates_stable },
      { value: "beta", label: m.updates_beta },
    ],
  },

  "appearance.theme": {
    section: "appearance",
    label: m.settings_color_scheme,
    description: m.settings_color_scheme_desc,
    initial: "system",
  },
  "appearance.accent": {
    section: "appearance",
    label: m.settings_accent,
    description: m.settings_accent_desc,
    initial: "graphite",
  },
  "appearance.sidebar": {
    section: "appearance",
    label: m.settings_sidebar,
    description: m.settings_sidebar_desc,
    initial: "default",
  },
  "appearance.material": {
    section: "appearance",
    label: m.settings_material,
    description: m.settings_material_desc,
    initial: "none",
  },
  "appearance.motion": {
    section: "appearance",
    label: m.settings_reduce_motion,
    description: m.settings_reduce_motion_desc,
    initial: false,
  },
  "general.default": {
    section: "general",
    label: m.pref_general_default,
    description: m.pref_general_default_help,
    initial: false,
  },
  "general.startup": {
    section: "general",
    label: m.pref_general_startup,
    description: m.pref_general_startup_help,
    initial: "Continue where I left off",
    options: [
      { value: "Continue where I left off", label: m.pref_general_startup_option_0 },
      { value: "Open New Tab", label: m.pref_general_startup_option_1 },
      { value: "Open specific pages", label: m.pref_general_startup_option_2 },
    ],
  },
  "general.restore": {
    section: "general",
    label: m.pref_general_restore,
    description: m.pref_general_restore_help,
    initial: true,
  },
  "general.import": {
    section: "general",
    label: m.pref_general_import,
    description: m.pref_general_import_help,
    initial: "",
  },
  "general.export": {
    section: "general",
    label: m.pref_general_export,
    description: m.pref_general_export_help,
    initial: "",
  },
  "appearance.density": {
    section: "appearance",
    label: m.pref_appearance_density,
    description: m.pref_appearance_density_help,
    initial: "Comfortable",
    options: [
      { value: "Comfortable", label: m.pref_appearance_density_option_0 },
      { value: "Compact", label: m.pref_appearance_density_option_1 },
    ],
  },
  "appearance.icons": {
    section: "appearance",
    label: m.pref_appearance_icons,
    description: m.pref_appearance_icons_help,
    initial: true,
  },
  "ntp.greeting": {
    section: "newtab",
    label: m.pref_ntp_greeting,
    description: m.pref_ntp_greeting_help,
    initial: true,
  },
  "ntp.personalize": {
    section: "newtab",
    label: m.pref_ntp_personalize,
    description: m.pref_ntp_personalize_help,
    initial: false,
  },
  "ntp.clock": {
    section: "newtab",
    label: m.pref_ntp_clock,
    description: m.pref_ntp_clock_help,
    initial: true,
  },
  "ntp.clock-format": {
    section: "newtab",
    label: m.pref_ntp_clock_format,
    description: m.pref_ntp_clock_format_help,
    initial: "system",
    options: [
      { value: "system", label: m.pref_ntp_clock_format_option_0 },
      { value: "12h", label: m.pref_ntp_clock_format_option_1 },
      { value: "24h", label: m.pref_ntp_clock_format_option_2 },
    ],
  },
  "ntp.tasks": {
    section: "newtab",
    label: m.pref_ntp_tasks,
    description: m.pref_ntp_tasks_help,
    initial: true,
  },
  "tabs.new-position": {
    section: "tabs",
    label: m.pref_tabs_new_position,
    description: m.pref_tabs_new_position_help,
    initial: "After current tab",
    options: [
      { value: "After current tab", label: m.pref_tabs_new_position_option_0 },
      { value: "End of list", label: m.pref_tabs_new_position_option_1 },
    ],
  },
  "tabs.close": {
    section: "tabs",
    label: m.pref_tabs_close,
    description: m.pref_tabs_close_help,
    initial: "Previously active tab",
    options: [
      { value: "Previously active tab", label: m.pref_tabs_close_option_0 },
      { value: "Next tab", label: m.pref_tabs_close_option_1 },
      { value: "Previous tab", label: m.pref_tabs_close_option_2 },
    ],
  },
  "tabs.duplicates": {
    section: "tabs",
    label: m.pref_tabs_duplicates,
    description: m.pref_tabs_duplicates_help,
    initial: true,
  },
  "tabs.folders": {
    section: "tabs",
    label: m.pref_tabs_folders,
    description: m.pref_tabs_folders_help,
    initial: true,
  },
  "tabs.archive": {
    section: "tabs",
    label: m.pref_tabs_archive,
    description: m.pref_tabs_archive_help,
    initial: "Never",
    options: [
      { value: "Never", label: m.pref_tabs_archive_option_0 },
      { value: "After 1 day", label: m.pref_tabs_archive_option_1 },
      { value: "After 7 days", label: m.pref_tabs_archive_option_2 },
      { value: "After 30 days", label: m.pref_tabs_archive_option_3 },
    ],
  },
  "tabs.sleep": {
    section: "tabs",
    label: m.pref_tabs_sleep,
    description: m.pref_tabs_sleep_help,
    initial: "30",
    range: { min: 5, max: 120, step: 5 },
  },
  "tabs.pins": {
    section: "tabs",
    label: m.pref_tabs_pins,
    description: m.pref_tabs_pins_help,
    initial: true,
  },
  "tabs.splits": {
    section: "tabs",
    label: m.pref_tabs_splits,
    description: m.pref_tabs_splits_help,
    initial: true,
  },
  "profiles.name": {
    section: "profiles",
    label: m.pref_profiles_name,
    description: m.pref_profiles_name_help,
    initial: "",
  },
  "profiles.icon": {
    section: "profiles",
    label: m.pref_profiles_icon,
    description: m.pref_profiles_icon_help,
    initial: "Initials",
    options: [
      { value: "Initials", label: m.pref_profiles_icon_option_0 },
      { value: "Icon", label: m.pref_profiles_icon_option_1 },
      { value: "Photo", label: m.pref_profiles_icon_option_2 },
    ],
  },
  "search.provider": {
    section: "search",
    label: m.pref_search_provider,
    description: m.pref_search_provider_help,
    initial: "DuckDuckGo",
    options: [
      { value: "DuckDuckGo", label: m.pref_search_provider_option_0 },
      { value: "Google", label: m.pref_search_provider_option_1 },
      { value: "Bing", label: m.pref_search_provider_option_2 },
      { value: "Brave", label: m.pref_search_provider_option_3 },
    ],
  },
  "search.suggestions": {
    section: "search",
    label: m.pref_search_suggestions,
    description: m.pref_search_suggestions_help,
    initial: false,
  },
  "search.history": {
    section: "search",
    label: m.pref_search_history,
    description: m.pref_search_history_help,
    initial: true,
  },
  "search.engines": {
    section: "search",
    label: m.pref_search_engines,
    description: m.pref_search_engines_help,
    initial: "",
  },
  "search.shortcuts": {
    section: "search",
    label: m.pref_search_shortcuts,
    description: m.pref_search_shortcuts_help,
    initial: "",
  },
  "privacy.blocking": {
    section: "privacy",
    label: m.pref_privacy_blocking,
    description: m.pref_privacy_blocking_help,
    initial: true,
  },
  "privacy.cookies": {
    section: "privacy",
    label: m.pref_privacy_cookies,
    description: m.pref_privacy_cookies_help,
    initial: "Block",
    options: [
      { value: "Block", label: m.pref_privacy_cookies_option_0 },
      { value: "Allow", label: m.pref_privacy_cookies_option_1 },
    ],
  },
  "privacy.https": {
    section: "privacy",
    label: m.pref_privacy_https,
    description: m.pref_privacy_https_help,
    initial: true,
  },
  "privacy.camera": {
    section: "privacy",
    label: m.pref_privacy_camera,
    description: m.pref_privacy_camera_help,
    initial: "Ask",
    options: [
      { value: "Ask", label: m.pref_privacy_camera_option_0 },
      { value: "Block", label: m.pref_privacy_camera_option_1 },
    ],
  },
  "privacy.microphone": {
    section: "privacy",
    label: m.pref_privacy_microphone,
    description: m.pref_privacy_microphone_help,
    initial: "Ask",
    options: [
      { value: "Ask", label: m.pref_privacy_microphone_option_0 },
      { value: "Block", label: m.pref_privacy_microphone_option_1 },
    ],
  },
  "privacy.location": {
    section: "privacy",
    label: m.pref_privacy_location,
    description: m.pref_privacy_location_help,
    initial: "Ask",
    options: [
      { value: "Ask", label: m.pref_privacy_location_option_0 },
      { value: "Block", label: m.pref_privacy_location_option_1 },
    ],
  },
  "privacy.notifications": {
    section: "privacy",
    label: m.pref_privacy_notifications,
    description: m.pref_privacy_notifications_help,
    initial: "Ask",
    options: [
      { value: "Ask", label: m.pref_privacy_notifications_option_0 },
      { value: "Block", label: m.pref_privacy_notifications_option_1 },
    ],
  },
  "privacy.exceptions": {
    section: "privacy",
    label: m.pref_privacy_exceptions,
    description: m.pref_privacy_exceptions_help,
    initial: "",
  },
  "privacy.clear": {
    section: "privacy",
    label: m.pref_privacy_clear,
    description: m.pref_privacy_clear_help,
    initial: "",
  },
  "passwords.offer": {
    section: "passwords",
    label: m.pref_passwords_offer,
    description: m.pref_passwords_offer_help,
    initial: true,
  },
  "passwords.fill": {
    section: "passwords",
    label: m.pref_passwords_fill,
    description: m.pref_passwords_fill_help,
    initial: true,
  },
  "passwords.addresses": {
    section: "passwords",
    label: m.pref_passwords_addresses,
    description: m.pref_passwords_addresses_help,
    initial: "",
  },
  "passwords.entries": {
    section: "passwords",
    label: m.pref_passwords_entries,
    description: m.pref_passwords_entries_help,
    initial: "",
  },
  "downloads.path": {
    section: "downloads",
    label: m.pref_downloads_path,
    description: m.pref_downloads_path_help,
    initial: "Downloads",
  },
  "downloads.ask": {
    section: "downloads",
    label: m.pref_downloads_ask,
    description: m.pref_downloads_ask_help,
    initial: false,
  },
  "downloads.notify": {
    section: "downloads",
    label: m.pref_downloads_notify,
    description: m.pref_downloads_notify_help,
    initial: true,
  },
  "downloads.clear": {
    section: "downloads",
    label: m.pref_downloads_clear,
    description: m.pref_downloads_clear_help,
    initial: "Manually",
    options: [
      { value: "Manually", label: m.pref_downloads_clear_option_0 },
      { value: "When Zephium closes", label: m.pref_downloads_clear_option_1 },
      { value: "After 7 days", label: m.pref_downloads_clear_option_2 },
    ],
  },
  "accessibility.text": {
    section: "shortcuts",
    label: m.pref_accessibility_text,
    description: m.pref_accessibility_text_help,
    initial: "Default",
    options: [
      { value: "Small", label: m.pref_accessibility_text_option_0 },
      { value: "Default", label: m.pref_accessibility_text_option_1 },
      { value: "Large", label: m.pref_accessibility_text_option_2 },
    ],
  },
  "accessibility.contrast": {
    section: "shortcuts",
    label: m.pref_accessibility_contrast,
    description: m.pref_accessibility_contrast_help,
    initial: false,
  },
  "shortcuts.editor": {
    section: "shortcuts",
    label: m.pref_shortcuts_editor,
    description: m.pref_shortcuts_editor_help,
    initial: "",
  },
  "languages.interface": {
    section: "languages",
    label: m.pref_languages_interface,
    description: m.pref_languages_interface_help,
    initial: "English",
    options: [{ value: "English", label: m.pref_languages_interface_option_0 }],
  },
  "languages.spelling": {
    section: "languages",
    label: m.pref_languages_spelling,
    description: m.pref_languages_spelling_help,
    initial: true,
  },
  "languages.format": {
    section: "languages",
    label: m.pref_languages_format,
    description: m.pref_languages_format_help,
    initial: "System",
    options: [
      { value: "System", label: m.pref_languages_format_option_0 },
      { value: "English (United States)", label: m.pref_languages_format_option_1 },
      { value: "English (United Kingdom)", label: m.pref_languages_format_option_2 },
    ],
  },
  "languages.preferred": {
    section: "languages",
    label: m.pref_languages_preferred,
    description: m.pref_languages_preferred_help,
    initial: "",
  },
  "focus.track": {
    section: "focus",
    label: m.pref_focus_track,
    description: m.pref_focus_track_help,
    initial: false,
  },
  "focus.retention": {
    section: "focus",
    label: m.pref_focus_retention,
    description: m.pref_focus_retention_help,
    initial: "30 days",
    options: [
      { value: "7 days", label: m.pref_focus_retention_option_0 },
      { value: "30 days", label: m.pref_focus_retention_option_1 },
      { value: "90 days", label: m.pref_focus_retention_option_2 },
    ],
  },
  "focus.exclusions": {
    section: "focus",
    label: m.pref_focus_exclusions,
    description: m.pref_focus_exclusions_help,
    initial: "",
  },
  "focus.rules": {
    section: "focus",
    label: m.pref_focus_rules,
    description: m.pref_focus_rules_help,
    initial: "",
  },
  "performance.sleep": {
    section: "performance",
    label: m.pref_performance_sleep,
    description: m.pref_performance_sleep_help,
    initial: true,
  },
  "performance.after": {
    section: "performance",
    label: m.pref_performance_after,
    description: m.pref_performance_after_help,
    initial: "15 minutes",
    options: [
      { value: "5 minutes", label: m.pref_performance_after_option_0 },
      { value: "15 minutes", label: m.pref_performance_after_option_1 },
      { value: "30 minutes", label: m.pref_performance_after_option_2 },
      { value: "1 hour", label: m.pref_performance_after_option_3 },
    ],
  },
  "performance.memory": {
    section: "performance",
    label: m.pref_performance_memory,
    description: m.pref_performance_memory_help,
    initial: "Balanced",
    options: [
      { value: "Balanced", label: m.pref_performance_memory_option_0 },
      { value: "Save memory", label: m.pref_performance_memory_option_1 },
      { value: "Keep tabs ready", label: m.pref_performance_memory_option_2 },
    ],
  },
  "performance.exceptions": {
    section: "performance",
    label: m.pref_performance_exceptions,
    description: m.pref_performance_exceptions_help,
    initial: "",
  },
  "work.decisions": {
    section: "ai",
    label: m.settings_decisions,
    description: m.settings_decisions_desc,
    initial: "recommended",
  },
  "work.decisions.key": {
    section: "ai",
    label: m.ai_jev_key_title,
    description: m.ai_jev_key_desc,
    initial: "",
  },
  "about.diagnostics": {
    section: "about",
    label: m.pref_about_diagnostics,
    description: m.pref_about_diagnostics_help,
    initial: "",
  },
  "about.reset": {
    section: "about",
    label: m.pref_about_reset,
    description: m.pref_about_reset_help,
    initial: "",
  },
} as const;
export type FieldId = keyof typeof fields;
