import * as m from "$shared/i18n/messages";
export const fields = {
  "privacy.cleanup": {
    preview: true,
    section: "privacy",
    label: m.privacy_on_exit,
    description: m.privacy_on_exit_help,
    initial: false,
  },
  "privacy.popups": {
    preview: true,
    section: "privacy",
    label: m.permission_popups,
    description: m.privacy_popups_help,
    initial: "Block",
    options: [
      { value: "Ask", label: m.permission_ask },
      { value: "Allow", label: m.permission_allow },
      { value: "Block", label: m.permission_block },
    ],
  },
  "privacy.clipboard": {
    preview: true,
    section: "privacy",
    label: m.permission_clipboard,
    description: m.privacy_clipboard_help,
    initial: "Ask",
    options: [
      { value: "Ask", label: m.permission_ask },
      { value: "Allow", label: m.permission_allow },
      { value: "Block", label: m.permission_block },
    ],
  },
  "privacy.automatic-downloads": {
    preview: true,
    section: "privacy",
    label: m.permission_automatic_downloads,
    description: m.privacy_downloads_help,
    initial: "Ask",
    options: [
      { value: "Ask", label: m.permission_ask },
      { value: "Allow", label: m.permission_allow },
      { value: "Block", label: m.permission_block },
    ],
  },
  "privacy.sound": {
    preview: true,
    section: "privacy",
    label: m.permission_sound,
    description: m.privacy_sound_help,
    initial: "Allow",
    options: [
      { value: "Ask", label: m.permission_ask },
      { value: "Allow", label: m.permission_allow },
      { value: "Block", label: m.permission_block },
    ],
  },

  "appearance.theme": {
    section: "appearance",
    label: m.settings_color_scheme,
    description: m.settings_color_scheme_desc,
    initial: "system",
  },
  "appearance.accent": {
    section: "appearance",
    label: m.settings_accent,
    description: m.settings_accent_desc,
    initial: "graphite",
  },
  "appearance.sidebar": {
    section: "appearance",
    label: m.settings_sidebar,
    description: m.settings_sidebar_desc,
    initial: "default",
  },
  "appearance.material": {
    section: "appearance",
    label: m.settings_material,
    description: m.settings_material_desc,
    initial: "none",
  },
  "appearance.motion": {
    section: "appearance",
    label: m.settings_reduce_motion,
    description: m.settings_reduce_motion_desc,
    initial: false,
  },
  "general.default": {
    section: "general",
    label: m.pref_general_default,
    description: m.pref_general_default_help,
    initial: false,
  },
  "general.startup": {
    section: "general",
    label: m.pref_general_startup,
    description: m.pref_general_startup_help,
    initial: "continue",
    options: [
      { value: "continue", label: m.pref_general_startup_option_0 },
      { value: "new-tab", label: m.pref_general_startup_option_1 },
    ],
  },
  "general.import": {
    section: "general",
    label: m.pref_general_import,
    description: m.pref_general_import_help,
    initial: "",
  },
  "general.export": {
    preview: true,
    section: "general",
    label: m.pref_general_export,
    description: m.pref_general_export_help,
    initial: "",
  },
  "appearance.density": {
    section: "appearance",
    label: m.pref_appearance_density,
    description: m.pref_appearance_density_help,
    initial: "comfortable",
    options: [
      { value: "comfortable", label: m.pref_appearance_density_option_0 },
      { value: "compact", label: m.pref_appearance_density_option_1 },
    ],
  },
  "ntp.greeting": {
    section: "newtab",
    label: m.pref_ntp_greeting,
    description: m.pref_ntp_greeting_help,
    initial: true,
  },
  "ntp.personalize": {
    section: "newtab",
    label: m.pref_ntp_personalize,
    description: m.pref_ntp_personalize_help,
    initial: false,
  },
  "ntp.clock": {
    section: "newtab",
    label: m.pref_ntp_clock,
    description: m.pref_ntp_clock_help,
    initial: true,
  },
  "ntp.clock-format": {
    section: "newtab",
    label: m.pref_ntp_clock_format,
    description: m.pref_ntp_clock_format_help,
    initial: "system",
    options: [
      { value: "system", label: m.pref_ntp_clock_format_option_0 },
      { value: "12h", label: m.pref_ntp_clock_format_option_1 },
      { value: "24h", label: m.pref_ntp_clock_format_option_2 },
    ],
  },
  "ntp.tasks": {
    section: "newtab",
    label: m.pref_ntp_tasks,
    description: m.pref_ntp_tasks_help,
    initial: true,
  },
  "tabs.new-position": {
    section: "tabs",
    label: m.pref_tabs_new_position,
    description: m.pref_tabs_new_position_help,
    initial: "end",
    options: [
      { value: "end", label: m.pref_tabs_new_position_option_1 },
      { value: "after-current", label: m.pref_tabs_new_position_option_0 },
    ],
  },
  "tabs.close": {
    section: "tabs",
    label: m.pref_tabs_close,
    description: m.pref_tabs_close_help,
    initial: "next",
    options: [
      { value: "next", label: m.pref_tabs_close_option_1 },
      { value: "previous", label: m.pref_tabs_close_option_2 },
      { value: "recent", label: m.pref_tabs_close_option_0 },
    ],
  },
  "tabs.duplicates": {
    section: "tabs",
    label: m.pref_tabs_duplicates,
    description: m.pref_tabs_duplicates_help,
    initial: true,
  },
  "tabs.archive": {
    preview: true,
    section: "tabs",
    label: m.pref_tabs_archive,
    description: m.pref_tabs_archive_help,
    initial: "Never",
    options: [
      { value: "Never", label: m.pref_tabs_archive_option_0 },
      { value: "After 1 day", label: m.pref_tabs_archive_option_1 },
      { value: "After 7 days", label: m.pref_tabs_archive_option_2 },
      { value: "After 30 days", label: m.pref_tabs_archive_option_3 },
    ],
  },
  "profiles.name": {
    preview: true,
    section: "profiles",
    label: m.pref_profiles_name,
    description: m.pref_profiles_name_help,
    initial: "",
  },
  "profiles.icon": {
    preview: true,
    section: "profiles",
    label: m.pref_profiles_icon,
    description: m.pref_profiles_icon_help,
    initial: "Initials",
    options: [
      { value: "Initials", label: m.pref_profiles_icon_option_0 },
      { value: "Icon", label: m.pref_profiles_icon_option_1 },
      { value: "Photo", label: m.pref_profiles_icon_option_2 },
    ],
  },
  "search.provider": {
    section: "search",
    label: m.pref_search_provider,
    description: m.pref_search_provider_help,
    initial: "DuckDuckGo",
    options: [
      { value: "DuckDuckGo", label: m.pref_search_provider_option_0 },
      { value: "Google", label: m.pref_search_provider_option_1 },
      { value: "Bing", label: m.pref_search_provider_option_2 },
      { value: "Brave", label: m.pref_search_provider_option_3 },
    ],
  },
  "search.suggestions": {
    section: "search",
    label: m.pref_search_suggestions,
    description: m.pref_search_suggestions_help,
    initial: false,
  },
  "search.history": {
    section: "search",
    label: m.pref_search_history,
    description: m.pref_search_history_help,
    initial: true,
  },
  "search.engines": {
    section: "search",
    label: m.pref_search_engines,
    description: m.pref_search_engines_help,
    initial: "",
  },
  "privacy.blocking": {
    section: "privacy",
    label: m.pref_privacy_blocking,
    description: m.pref_privacy_blocking_help,
    initial: true,
  },
  "privacy.camera": {
    preview: true,
    section: "privacy",
    label: m.pref_privacy_camera,
    description: m.pref_privacy_camera_help,
    initial: "Ask",
    options: [
      { value: "Ask", label: m.pref_privacy_camera_option_0 },
      { value: "Block", label: m.pref_privacy_camera_option_1 },
    ],
  },
  "privacy.microphone": {
    preview: true,
    section: "privacy",
    label: m.pref_privacy_microphone,
    description: m.pref_privacy_microphone_help,
    initial: "Ask",
    options: [
      { value: "Ask", label: m.pref_privacy_microphone_option_0 },
      { value: "Block", label: m.pref_privacy_microphone_option_1 },
    ],
  },
  "privacy.location": {
    preview: true,
    section: "privacy",
    label: m.pref_privacy_location,
    description: m.pref_privacy_location_help,
    initial: "Ask",
    options: [
      { value: "Ask", label: m.pref_privacy_location_option_0 },
      { value: "Block", label: m.pref_privacy_location_option_1 },
    ],
  },
  "privacy.notifications": {
    preview: true,
    section: "privacy",
    label: m.pref_privacy_notifications,
    description: m.pref_privacy_notifications_help,
    initial: "Ask",
    options: [
      { value: "Ask", label: m.pref_privacy_notifications_option_0 },
      { value: "Block", label: m.pref_privacy_notifications_option_1 },
    ],
  },
  "privacy.exceptions": {
    preview: true,
    section: "privacy",
    label: m.pref_privacy_exceptions,
    description: m.pref_privacy_exceptions_help,
    initial: "",
  },
  "privacy.clear": {
    section: "privacy",
    label: m.pref_privacy_clear,
    description: m.pref_privacy_clear_help,
    initial: "",
  },
  "downloads.path": {
    section: "general",
    label: m.pref_downloads_path,
    description: m.pref_downloads_path_help,
    initial: "Downloads",
  },
  "downloads.ask": {
    section: "general",
    label: m.pref_downloads_ask,
    description: m.pref_downloads_ask_help,
    initial: false,
  },
  "accessibility.text": {
    section: "shortcuts",
    label: m.pref_accessibility_text,
    description: m.pref_accessibility_text_help,
    initial: "default",
    options: [
      { value: "small", label: m.pref_accessibility_text_option_0 },
      { value: "default", label: m.pref_accessibility_text_option_1 },
      { value: "large", label: m.pref_accessibility_text_option_2 },
    ],
  },
  "accessibility.contrast": {
    section: "shortcuts",
    label: m.pref_accessibility_contrast,
    description: m.pref_accessibility_contrast_help,
    initial: false,
  },
  "languages.interface": {
    section: "languages",
    label: m.pref_languages_interface,
    description: m.pref_languages_interface_help,
    initial: "system",
  },
  "focus.track": {
    preview: true,
    section: "focus",
    label: m.pref_focus_track,
    description: m.pref_focus_track_help,
    initial: false,
  },
  "focus.retention": {
    preview: true,
    section: "focus",
    label: m.pref_focus_retention,
    description: m.pref_focus_retention_help,
    initial: "30 days",
    options: [
      { value: "7 days", label: m.pref_focus_retention_option_0 },
      { value: "30 days", label: m.pref_focus_retention_option_1 },
      { value: "90 days", label: m.pref_focus_retention_option_2 },
    ],
  },
  "focus.exclusions": {
    preview: true,
    section: "focus",
    label: m.pref_focus_exclusions,
    description: m.pref_focus_exclusions_help,
    initial: "",
  },
  "focus.rules": {
    preview: true,
    section: "focus",
    label: m.pref_focus_rules,
    description: m.pref_focus_rules_help,
    initial: "",
  },
  "performance.sleep": {
    preview: true,
    section: "performance",
    label: m.pref_performance_sleep,
    description: m.pref_performance_sleep_help,
    initial: true,
  },
  "performance.after": {
    preview: true,
    section: "performance",
    label: m.pref_performance_after,
    description: m.pref_performance_after_help,
    initial: "15 minutes",
    options: [
      { value: "5 minutes", label: m.pref_performance_after_option_0 },
      { value: "15 minutes", label: m.pref_performance_after_option_1 },
      { value: "30 minutes", label: m.pref_performance_after_option_2 },
      { value: "1 hour", label: m.pref_performance_after_option_3 },
    ],
  },
  "performance.memory": {
    preview: true,
    section: "performance",
    label: m.pref_performance_memory,
    description: m.pref_performance_memory_help,
    initial: "Balanced",
    options: [
      { value: "Balanced", label: m.pref_performance_memory_option_0 },
      { value: "Save memory", label: m.pref_performance_memory_option_1 },
      { value: "Keep tabs ready", label: m.pref_performance_memory_option_2 },
    ],
  },
  "performance.exceptions": {
    preview: true,
    section: "performance",
    label: m.pref_performance_exceptions,
    description: m.pref_performance_exceptions_help,
    initial: "",
  },
  "work.decisions": {
    section: "work",
    label: m.settings_decisions,
    description: m.settings_decisions_desc,
    initial: "recommended",
  },
  "about.reset": {
    section: "about",
    label: m.pref_about_reset,
    description: m.pref_about_reset_help,
    initial: "",
  },
} as const;
export type FieldId = keyof typeof fields;
