// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	tabsBootstrap: () => __TAURI_INVOKE<void>("tabs_bootstrap"),
	tabsOpen: () => __TAURI_INVOKE<OperationAdmission>("tabs_open"),
	tabsActivate: (id: string) => __TAURI_INVOKE<OperationAdmission>("tabs_activate", { id }),
	tabsClose: (id: string) => __TAURI_INVOKE<OperationAdmission>("tabs_close", { id }),
	tabsNavigate: (id: string, input: string) => __TAURI_INVOKE<OperationAdmission>("tabs_navigate", { id, input }),
	tabsReload: (id: string) => __TAURI_INVOKE<OperationAdmission>("tabs_reload", { id }),
	tabsBack: (id: string) => __TAURI_INVOKE<OperationAdmission>("tabs_back", { id }),
	tabsForward: (id: string) => __TAURI_INVOKE<OperationAdmission>("tabs_forward", { id }),
	tabsSplit: (other: string) => __TAURI_INVOKE<OperationAdmission>("tabs_split", { other }),
	tabsUnsplit: () => __TAURI_INVOKE<OperationAdmission>("tabs_unsplit"),
	extensionActionInvoke: (profileId: string, installId: string, runtimeGeneration: string, actionRevision: string, anchorX: number | null, anchorY: number | null, anchorWidth: number | null, anchorHeight: number | null) => __TAURI_INVOKE<OperationAdmission>("extension_action_invoke", { profileId, installId, runtimeGeneration, actionRevision, anchorX, anchorY, anchorWidth, anchorHeight }),
	/**
	 *  Opens or closes the one focused-profile management subscription.
	 *  This is deliberately an explicit, non-polling visibility signal: the Shell
	 *  retains authenticated management metadata only while privileged chrome is
	 *  displaying it and performs no extension repository work at browser startup.
	 */
	extensionManagementSetVisible: (visible: boolean) => __TAURI_INVOKE<boolean>("extension_management_set_visible", { visible }),
	/**
	 *  Requests the one product-sealed extension catalog synchronization. The
	 *  caller supplies no URL, profile, package, runtime target, or selection;
	 *  those authorities were bound immutably before the worker was launched.
	 */
	extensionDistributionRefresh: () => __TAURI_INVOKE<ExtensionDistributionRefreshAdmissionView>("extension_distribution_refresh"),
	extensionManagementInstall: (candidateIndex: number, catalogRevision: string, selection: ExtensionInstallGrantSelectionInput) => __TAURI_INVOKE<OperationAdmission>("extension_management_install", { candidateIndex, catalogRevision, selection }),
	extensionManagementSetEnabled: (installId: string, catalogRevision: string, installRevision: string, enabled: boolean) => __TAURI_INVOKE<OperationAdmission>("extension_management_set_enabled", { installId, catalogRevision, installRevision, enabled }),
	extensionManagementUninstall: (installId: string, catalogRevision: string, installRevision: string) => __TAURI_INVOKE<OperationAdmission>("extension_management_uninstall", { installId, catalogRevision, installRevision }),
	/**
	 *  Answers only the exact Shell-projected native permission prompt. The four
	 *  identities are short-lived stale fences; permission names never cross this
	 *  command boundary and the actor remains the sole owner of the retained
	 *  request payload.
	 */
	extensionRuntimeGrantRespond: (profileId: string, installId: string, runtimeGeneration: string, requestId: string, allow: boolean) => __TAURI_INVOKE<OperationAdmission>("extension_runtime_grant_respond", { profileId, installId, runtimeGeneration, requestId, allow }),
	/**
	 *  Answers only the exact Shell-projected foreground page request. Origin and
	 *  capability names are intentionally absent: chrome can choose a disposition
	 *  but cannot mint or alter authority.
	 */
	pagePermissionRespond: (profileId: string, itemId: string, requestId: string, decision: PagePermissionPromptDecisionInput) => __TAURI_INVOKE<OperationAdmission>("page_permission_respond", { profileId, itemId, requestId, decision }),
	blockerStatus: () => typedError<BlockerStatusView, null>(__TAURI_INVOKE("blocker_status")),
	blockerSetEnabled: (enabled: boolean) => __TAURI_INVOKE<OperationAdmission>("blocker_set_enabled", { enabled }),
	blockerRetry: (failedGeneration: string) => __TAURI_INVOKE<OperationAdmission>("blocker_retry", { failedGeneration }),
	blockerRefreshSources: () => __TAURI_INVOKE<OperationAdmission>("blocker_refresh_sources"),
	profilesDelete: (profile: string) => __TAURI_INVOKE<OperationAdmission>("profiles_delete", { profile }),
	operationStatus: (operationId: string) => __TAURI_INVOKE<OperationStatus>("operation_status", { operationId }),
	operationsReconcile: () => __TAURI_INVOKE<OperationDisposition[]>("operations_reconcile"),
	operationAcknowledge: (operationId: string) => __TAURI_INVOKE<boolean>("operation_acknowledge", { operationId }),
	runCommand: (id: string) => __TAURI_INVOKE<OperationAdmission>("run_command", { id }),
	panelHide: () => __TAURI_INVOKE<void>("panel_hide"),
	settingGet: (key: string) => __TAURI_INVOKE<string | null>("setting_get", { key }),
	settingSet: (key: string, value: string) => __TAURI_INVOKE<OperationAdmission>("setting_set", { key, value }),
	uiInfo: () => __TAURI_INVOKE<UiInfo>("ui_info"),
	uiReady: () => __TAURI_INVOKE<boolean>("ui_ready"),
	menuPopup: (x: number | null, y: number | null) => __TAURI_INVOKE<boolean>("menu_popup", { x, y }),
	addMenuPopup: (x: number | null, y: number | null, canSplit: boolean) => __TAURI_INVOKE<boolean>("add_menu_popup", { x, y, canSplit }),
	tabMenuPopup: (id: string, x: number | null, y: number | null, canSplit: boolean) => __TAURI_INVOKE<boolean>("tab_menu_popup", { id, x, y, canSplit }),
	profileMenuPopup: (x: number | null, y: number | null) => __TAURI_INVOKE<boolean>("profile_menu_popup", { x, y }),
	sidebarMenuPopup: (x: number | null, y: number | null) => __TAURI_INVOKE<boolean>("sidebar_menu_popup", { x, y }),
	launcherSearch: (query: string) => __TAURI_INVOKE<void>("launcher_search", { query }),
	launcherRun: (action: SearchAction) => __TAURI_INVOKE<OperationAdmission>("launcher_run", { action }),
	sidebarSetWidth: (width: number | null) => __TAURI_INVOKE<void>("sidebar_set_width", { width }),
	tabDragOver: (x: number | null, y: number | null) => __TAURI_INVOKE<void>("tab_drag_over", { x, y }),
	tabDrop: (id: string, x: number | null, y: number | null) => __TAURI_INVOKE<OperationAdmission>("tab_drop", { id, x, y }),
	dividerGrab: (x: number | null, y: number | null) => __TAURI_INVOKE<void>("divider_grab", { x, y }),
	dividerDrag: (x: number | null, y: number | null) => __TAURI_INVOKE<void>("divider_drag", { x, y }),
	dividerRelease: (x: number | null, y: number | null) => __TAURI_INVOKE<OperationAdmission>("divider_release", { x, y }),
};

/** Events */
export const events = {
	blockerStatusChanged: makeEvent<BlockerStatusChanged>("blocker-status-changed"),
	extensionActionFailed: makeEvent<ExtensionActionFailed>("extension-action-failed"),
	extensionActionsChanged: makeEvent<ExtensionActionsChanged>("extension-actions-changed"),
	extensionDistributionChanged: makeEvent<ExtensionDistributionChanged>("extension-distribution-changed"),
	extensionManagementAvailabilityChanged: makeEvent<ExtensionManagementAvailabilityChanged>("extension-management-availability-changed"),
	extensionManagementChanged: makeEvent<ExtensionManagementChanged>("extension-management-changed"),
	extensionRuntimeGrantPromptChanged: makeEvent<ExtensionRuntimeGrantPromptChanged>("extension-runtime-grant-prompt-changed"),
	itemsChanged: makeEvent<ItemsChanged>("items-changed"),
	layoutChanged: makeEvent<LayoutChanged>("layout-changed"),
	operationProcessed: makeEvent<OperationProcessed>("operation-processed"),
	pagePermissionPromptChanged: makeEvent<PagePermissionPromptChanged>("page-permission-prompt-changed"),
	runtimeStatusChanged: makeEvent<RuntimeStatusChanged>("runtime-status-changed"),
	searchChanged: makeEvent<SearchChanged>("search-changed"),
	tabChanged: makeEvent<TabChanged>("tab-changed"),
	uiCommand: makeEvent<UiCommand>("ui-command"),
};

/* Types */
/**
 *  Stable diagnostics classification. Native/parser text and filter content
 *  never cross the privileged IPC boundary.
 */
export type BlockerFailure = "generation_exhausted" | "compiler_dispatch_rejected" | "compiler_unavailable" | "compile_source_unavailable" | "compile_invalid_source" | "compile_resource_limit" | "compile_internal" | "compiled_artifact_mismatch" | "native_dispatch_rejected" | "native_unsupported" | "native_unsupported_artifact" | "native_invalid_artifact" | "native_compilation" | "native_installation" | "native_cleanup" | "native_superseded" | "contradictory_native_settlement";

export type BlockerPhase = "unavailable" | "uninitialized" | "compiling" | "installing" | "ready" | "failed" | "retired";

/**
 *  Authority of the focused profile's durable blocker preference.
 *  `Reconciling` and `Unavailable` are intentionally distinct from native
 *  policy state: the browser may still know which generation is installed
 *  while refusing to guess what durable preference should replace it.
 */
export type BlockerPreferenceState = "authoritative" | "updating" | "reconciling" | "unavailable";

/**
 *  Effective protection for the focused profile's exact native policy.
 *  This is derived in Rust from both desired and retained state. Privileged
 *  chrome must not infer protection from a pending preference and accidentally
 *  present a retained allow-all generation as active blocking.
 */
export type BlockerProtection = "disabled" | "pending" | "active" | "degraded" | "unavailable";

/**
 *  Exact coverage of the generation which native code proved applied.
 *  Counts are bounded far below JavaScript's exact-integer ceiling by the
 *  blocker compiler's hard rule limits.
 */
export type BlockerRuleCoverage = {
	source_rules: number,
	accepted_rules: number,
	rejected_rules: number,
	platform_omitted_rules: number,
	platform_approximated_rules: number,
	platform_resource_approximated_rules: number,
	platform_source_kind_approximated_rules: number,
	platform_attribution_approximated_rules: number,
	blocking_rule_entries: number,
};

/**
 *  Volatile, process-local health counters for the exact applied runtime
 *  matcher. Decimal strings preserve the full saturating `u64` range in
 *  JavaScript. These counters are never persisted and contain no request,
 *  origin, URL, profile, or rule identity.
 */
export type BlockerRuntimeDiagnostics = {
	total_decisions: string,
	candidate_budget_exhausted: string,
	matcher_unavailable: string,
	matcher_unprepared: string,
	attribution_unavailable: string,
	evaluation_errors: string,
};

/**
 *  Stable package-refresh failure category. Endpoint, parser, and native
 *  strings are intentionally never forwarded to privileged JavaScript.
 */
export type BlockerSourceFailure = "transport" | "metadata" | "clock" | "manifest" | "target" | "license" | "rollback" | "storage" | "catalog" | "internal";

/**
 *  Exact authenticated identities for source-package transition diagnostics.
 *  This is boxed in [`BlockerStatusView`] so infrequent debug strings do not
 *  inflate every application projection on the shell actor's hot path.
 */
export type BlockerSourceIdentities = {
	package_manifest_sha256: string | null,
	candidate_revision: string | null,
	candidate_manifest_sha256: string | null,
	installed_manifest_sha256: string | null,
};

/**  Sanitized state of the authenticated filter-package supply chain. */
export type BlockerSourcePhase = "not_configured" | "durable_activation_unsupported" | "storage_unavailable" | "clock_unsafe" | "idle" | "fresh" | "stale" | "refreshing" | "failed" | "shutdown";

/**  Authority which admitted the displayed filter package. */
export type BlockerSourceProvenance = "release_bundle" | "tuf_repository";

export type BlockerStatusChanged = BlockerStatusView;

/**
 *  Read-only, focused-profile diagnostics delivered only to privileged main
 *  chrome. It deliberately contains no profile selector, URL, origin, request
 *  metadata, native error string, or filter-list text. Runtime health is
 *  represented only by volatile aggregate counters.
 */
export type BlockerStatusView = {
	projection_revision: string,
	protection: BlockerProtection,
	phase: BlockerPhase,
	preference: BlockerPreferenceState,
	config_revision: string | null,
	desired_enabled: boolean | null,
	applied_enabled: boolean | null,
	desired_generation: string | null,
	retained_generation: string | null,
	failure: BlockerFailure | null,
	retryable: boolean,
	retries_remaining: number,
	/**
	 *  Boxed with the other diagnostic-only payloads so ordinary projection
	 *  queue entries do not carry the full coverage report inline.
	 */
	applied_coverage: BlockerRuleCoverage | null,
	/**
	 *  Boxed because the six decimal counters are diagnostic-only and should
	 *  not inflate every projection enum value on the actor/UI hot path.
	 */
	runtime_diagnostics: BlockerRuntimeDiagnostics | null,
	source_phase: BlockerSourcePhase,
	source_failure: BlockerSourceFailure | null,
	source_package_revision: string | null,
	source_installed_revision: string | null,
	source_package_provenance: BlockerSourceProvenance | null,
	source_installed_provenance: BlockerSourceProvenance | null,
	source_identities: BlockerSourceIdentities | null,
	source_package_created_unix: string | null,
	source_package_expires_unix: string | null,
	source_package_stale: boolean | null,
	/**
	 *  Advisory source update cadence. This never downgrades a healthy
	 *  release-bundled policy.
	 */
	source_refresh_due: boolean,
	source_count: number | null,
	source_bytes: number | null,
	source_activation_pending: boolean,
	source_material_repair_pending: boolean,
	source_material_repair_retry_pending: boolean,
	source_repair_retry_pending: boolean,
	source_last_refresh_attempt_unix: string | null,
	source_refresh_operation: string | null,
	/**  Authoritative source-policy capability for the focused profile. */
	can_enable: boolean,
	/**  Authoritative refresh admission capability for the active supply mode. */
	can_refresh_sources: boolean,
};

/**
 *  Split divider hit-strip in window logical coordinates; the chrome renders
 *  these as drag targets on platforms without native stage dividers.
 */
export type DividerView = {
	x: number | null,
	y: number | null,
	width: number | null,
	height: number | null,
	vertical: boolean,
};

export type ExtensionActionFailed = ExtensionActionFailedView;

/**
 *  Actor-ordered, context-bound transient failure notice. The revision lets
 *  privileged chrome discard a delayed eval and present each current failure
 *  at most once; the profile/tab join prevents a late native refusal from
 *  appearing after the user has switched context.
 */
export type ExtensionActionFailedView = {
	projection_revision: string,
	profile_id: string,
	tab_id: string,
	reason: ExtensionActionFailure,
};

/**
 *  Closed, sanitized reason why a trusted toolbar gesture could not complete.
 *  Native strings, extension content, URLs, and runtime identities are never
 *  forwarded through this transient user-notice channel.
 */
export type ExtensionActionFailure = "invalid_request" | "runtime_unavailable" | "runtime_superseded" | "tab_unavailable" | "tab_discarded" | "action_unavailable" | "action_disabled" | "capacity_exceeded" | "popup_unavailable" | "popup_capacity_exceeded" | "native_admission_failed" | "shutting_down" | "unsupported_platform";

/**
 *  Non-authorizing identity for one live extension runtime. Privileged chrome
 *  may echo this value only as part of an action gesture; the Shell rejoins it
 *  to the focused profile, active tab, browser-surface generation, and current
 *  action revision before any native work is admitted.
 */
export type ExtensionActionRuntimeView = {
	install_id: string,
	/**
	 *  Process-local nonzero generation, encoded as fixed-width hexadecimal
	 *  so JavaScript never rounds a Rust `u64`.
	 */
	generation: string,
};

/**
 *  One effective toolbar action for the focused profile's active logical tab.
 *  Labels and badges are bounded before this projection is constructed. The
 *  optional icon is the canonical base64 encoding of exactly 32x32 RGBA bytes;
 *  privileged chrome performs no extension-controlled image decoding.
 */
export type ExtensionActionView = {
	runtime: ExtensionActionRuntimeView,
	revision: string,
	label: string,
	badge: string,
	icon_rgba_base64: string | null,
	enabled: boolean,
	presents_popup: boolean,
	unread_badge: boolean,
};

export type ExtensionActionsChanged = ExtensionActionsView;

/**
 *  Exact replacement action cohort. An empty `actions` collection removes all
 *  previously visible actions for this profile/tab. The frame additionally
 *  joins `profile_id` and `tab_id` to its current Items projection, so event
 *  reordering cannot expose a stale action after focus changes.
 */
export type ExtensionActionsView = {
	projection_revision: string,
	profile_id: string,
	tab_id: string | null,
	actions: ExtensionActionView[],
};

export type ExtensionDistributionChanged = ExtensionDistributionView;

/**
 *  Redacted product-distribution failure reason. Network and native error
 *  strings never cross the privileged IPC boundary.
 */
export type ExtensionDistributionFailureReasonView = "acquisition" | "busy" | "service_unavailable" | "service_rejected" | "service_failed_closed" | "settlement_timed_out" | "settlement_lost" | "submission_panicked" | "outcome_unresolved" | "activation_rejected" | "accounting";

/**  Stable distribution failure stage exposed only to privileged chrome. */
export type ExtensionDistributionFailureStageView = { type: "catalog" } | { type: "package_fetch"; index: number } | { type: "package_provision"; index: number } | { type: "catalog_activation" };

/**
 *  Closed response for the argument-free product update trigger. This is an
 *  admission result, not completion; authoritative progress and settlement
 *  continue to arrive through `ExtensionDistributionChanged`.
 */
export type ExtensionDistributionRefreshAdmissionView = "accepted" | "busy" | "quarantined" | "unavailable" | "shutting_down";

/**  Exact replacement state for the dormant product distribution worker. */
export type ExtensionDistributionStateView = { phase: "idle" } | { phase: "synchronizing" } | { phase: "ready"; package_count: number; materialized_packages: number; reused_packages: number; exact_retries: number; newly_activated: boolean } | { phase: "failed"; stage: ExtensionDistributionFailureStageView; reason: ExtensionDistributionFailureReasonView } | { phase: "quarantined"; stage: ExtensionDistributionFailureStageView; reason: ExtensionDistributionFailureReasonView } | { phase: "shutdown" };

/**  Shell-revisioned product-distribution status for privileged extension UI. */
export type ExtensionDistributionView = {
	projection_revision: string,
	state: ExtensionDistributionStateView,
};

/**
 *  One authenticated package offered by Zephium's current curated catalog.
 *  `candidate_index` is an opaque, short-lived selector into the exact
 *  revisioned catalog retained by Shell. Privileged chrome may only echo it;
 *  it conveys no package, repository, profile, or permission authority.
 */
export type ExtensionInstallCandidateView = {
	candidate_index: number,
	name: string,
	description: string | null,
	author: string | null,
	version: string,
	source: ExtensionManagementSourceView,
	/**  Decimal Unix seconds of the authenticated Verified catalog release. */
	verified_catalog_unix: string | null,
	provenance: ExtensionManagementProvenanceView | null,
	required_api: string[],
	required_hosts: string[],
	/**
	 *  Canonically ordered optional API grants. The frontend returns only
	 *  selected array indexes; Shell rejoins them to its retained candidate.
	 */
	optional_api: string[],
	/**  Canonically ordered optional host grants. */
	optional_hosts: string[],
	supports_file_access: boolean,
	compatibility: ExtensionManagementCompatibilityView,
	limitations: ExtensionManagementLimitationView[],
};

/**
 *  Installs only a candidate from Shell's latest authenticated, retained
 *  management catalog. The frontend supplies no profile, package path,
 *  manifest declaration, or permission-name authority.
 */
export type ExtensionInstallGrantSelectionInput = {
	optional_api_indices: number[],
	optional_host_indices: number[],
	file_access: boolean,
	private_access: boolean,
};

export type ExtensionManagementAvailabilityChanged = ExtensionManagementAvailabilityChangedView;

/**  Actor-ordered projection of extension-management product availability. */
export type ExtensionManagementAvailabilityChangedView = {
	projection_revision: string,
	availability: ExtensionManagementAvailabilityView,
};

/**
 *  Process-immutable product availability for the extension-management UX.
 *  This is a non-authorizing presentation fact. It carries no catalog,
 *  package, profile, repository, or runtime identity.
 */
export type ExtensionManagementAvailabilityView = "configured" | "not_configured" | "unavailable";

export type ExtensionManagementChanged = ExtensionManagementView;

/**  Reviewed compatibility of the exact authenticated manifest. */
export type ExtensionManagementCompatibilityView = "compatible" | "degraded";

/**  One authenticated installed extension in browser-owned management UI. */
export type ExtensionManagementEntryView = {
	install_id: string,
	install_revision: string,
	name: string,
	description: string | null,
	author: string | null,
	version: string,
	source: ExtensionManagementSourceView,
	/**  Decimal Unix seconds of the authenticated Verified catalog release. */
	verified_catalog_unix: string | null,
	provenance: ExtensionManagementProvenanceView | null,
	runtime: ExtensionManagementRuntimeView,
	/**  Present only when `runtime` is `active`. */
	runtime_generation: string | null,
	grants: ExtensionManagementGrantView,
	compatibility: ExtensionManagementCompatibilityView,
	limitations: ExtensionManagementLimitationView[],
};

/**  Non-authorizing summary of the atomic grant row joined to an install. */
export type ExtensionManagementGrantView = {
	initialized: boolean,
	revision: string | null,
	api_grants: number,
	host_grants: number,
	file_access: boolean,
	private_access: boolean,
};

/**  One browser-owned explanation for a reviewed platform degradation. */
export type ExtensionManagementLimitationView = { type: "api_permission"; name: string } | { type: "host_access" } | { type: "background" } | { type: "action" } | { type: "offscreen" } | { type: "native_messaging" } | { type: "browser_override" } | { type: "extension_pages_csp" } | { type: "sandbox" } | { type: "content_scripts" } | { type: "web_accessible_resources" } | { type: "minimum_browser_version" } | { type: "commands" } | { type: "side_panel" } | { type: "managed_storage" };

/**  Settlement of the focused profile's lazy installed-extension projection. */
export type ExtensionManagementPhase = "loading" | "ready" | "not_configured" | "unavailable" | "rejected" | "failed_closed";

/**  Browser-authenticated, inert upstream identity for extension management UI. */
export type ExtensionManagementProvenanceView = {
	source_url: string,
	upstream_version: string,
	license_expression: string,
	attribution: string,
};

/**  Process-local regular-runtime state for one installed extension. */
export type ExtensionManagementRuntimeView = "disabled" | "pending_activation" | "active";

/**  Browser-authenticated acquisition/support lane for extension management UI. */
export type ExtensionManagementSourceView = "zephium_verified" | "external_compatibility" | "developer_local";

/**
 *  Exact replacement management cohort for the focused profile.
 *  Loading and failure phases always carry no catalog revision or rows, so a
 *  delayed failure cannot leave stale selectors actionable in privileged UI.
 */
export type ExtensionManagementView = {
	projection_revision: string,
	profile_id: string,
	phase: ExtensionManagementPhase,
	catalog_revision: string | null,
	entries: ExtensionManagementEntryView[],
	candidates: ExtensionInstallCandidateView[],
};

export type ExtensionRuntimeGrantPromptChanged = ExtensionRuntimeGrantPromptView;

/**
 *  One browser-owned optional-permission consent surface. Every identity is a
 *  short-lived echo token only; the Shell rejoins it to its retained native
 *  request before a user response can reach the serialized grant service.
 */
export type ExtensionRuntimeGrantPromptEntryView = {
	profile_id: string,
	install_id: string,
	runtime_generation: string,
	request_id: string,
	extension_name: string,
	api_permissions: string[],
	host_permissions: string[],
	private_context: boolean,
	/**
	 *  True after an Allow gesture while the durable grant transaction is in
	 *  flight. Chrome must disable both response buttons until replacement.
	 */
	processing: boolean,
};

/**
 *  Exact replacement for the process-wide permission prompt surface. `None`
 *  closes any prior prompt; Shell serializes the bounded native cohort so the
 *  frame never chooses request ordering.
 */
export type ExtensionRuntimeGrantPromptView = {
	projection_revision: string,
	prompt: ExtensionRuntimeGrantPromptEntryView | null,
};

export type ItemsChanged = ItemsState;

export type ItemsState = {
	projection_revision: string,
	/**
	 *  `None` is reserved for the frame's cold pre-bootstrap state. Native
	 *  snapshots are emitted only with an exact focused profile and space.
	 */
	profile: ProfileView | null,
	spaces: SpaceView[],
	active_space_id: string | null,
	nodes: SidebarNodeView[],
	/**  Every tab referenced by `nodes`, in the same pre-order traversal. */
	tabs: TabView[],
	active: string | null,
	split_group: SplitGroupView | null,
};

export type LayoutChanged = LayoutState;

export type LayoutState = {
	dividers: DividerView[],
};

/**
 *  Immediate result returned by a privileged IPC command. `accepted` with an
 *  `operation_id` means the mutation was successfully and non-evictably
 *  admitted to the shell's process-local ordered FIFO; it does not claim that
 *  later native/store work succeeded or survive a process restart. `accepted`
 *  without an id is reserved for a fully applied, privileged-UI-only action
 *  such as toggling the launcher.
 */
export type OperationAdmission = {
	operation_id: string | null,
	accepted: boolean,
};

/**
 *  The shell has processed an admitted operation in actor order. Consumers
 *  reconcile logical effects from authoritative projections. A deferred
 *  native navigation still resolves independently through engine events.
 *  Long-running profile deletion retains its id internally and emits this
 *  disposition exactly once, only after definitive rejection or both durable
 *  deletion phases complete; blocker preference mutations likewise retain
 *  their id through CAS and exact native settlement. Retry/reconciliation
 *  state is never mislabeled as successfully applied.
 */
export type OperationDisposition = {
	operation_id: string,
	outcome: OperationOutcome,
	reason: OperationReason,
};

/**
 *  The bounded terminal classification the actor can establish while
 *  processing an admitted operation. `Deferred` means native work was queued,
 *  an exact discard acknowledgement is still required, or a durable write
 *  became indeterminate and entered explicit reconciliation; it never means a
 *  page load, renderer callback, or unknown store transaction succeeded.
 */
export type OperationOutcome = "applied" | "no_op" | "rejected" | "native_admission_failed" | "deferred";

export type OperationProcessed = OperationDisposition;

/**
 *  Stable, non-page-derived detail for an operation outcome. Keeping this an
 *  enum prevents native errors, URLs, or attacker-controlled strings from
 *  becoming an unbounded privileged IPC/logging surface.
 */
export type OperationReason = "mutation_applied" | "state_unchanged" | "invalid_scope" | "no_focused_window" | "item_limit_reached" | "invalid_input" | "history_unavailable" | "layout_unavailable" | "unsupported_command" | "native_dispatch_rejected" | "native_work_pending" | "discard_completion_pending" | "store_work_pending" | "store_admission_rejected" | "store_conflict" | "store_outcome_unknown" | "store_reconciliation_failed" | "extension_enablement_pending" | "extension_activation_pending" | "content_policy_apply_failed" | "content_policy_source_unavailable" | "content_policy_source_refresh_pending" | "content_policy_source_refresh_failed" | "content_policy_sources_refreshed" | "profile_deletion_policy_rejected" | "profile_deletion_in_progress" | "profile_deletion_completed";

/**
 *  Process-local reconciliation state for an admitted mutation. Pending and
 *  processed entries are retained in a bounded fail-closed desktop ledger;
 *  processed entries remain queryable until privileged chrome acknowledges
 *  them. `Unknown` means the id was never admitted in this process, was already
 *  acknowledged, or belongs to a previous process lifetime.
 */
export type OperationStatus = { state: "unknown" } | { state: "pending" } | { state: "processed"; disposition: OperationDisposition };

/**
 *  Closed page capability names rendered by browser-owned chrome. Native
 *  permission strings and page-controlled labels never cross this boundary.
 */
export type PagePermissionKindView = "camera" | "microphone";

export type PagePermissionPromptChanged = PagePermissionPromptView;

export type PagePermissionPromptDecisionInput = "allow_once" | "always_allow" | "deny_once" | "always_deny";

/**
 *  One exact, foreground page-permission request. Every identity is an opaque
 *  stale fence: privileged chrome may only echo it back to the Shell.
 */
export type PagePermissionPromptEntryView = {
	profile_id: string,
	item_id: string,
	request_id: string,
	origin: string,
	kinds: PagePermissionKindView[],
	/**  False for ephemeral profiles; chrome must not offer durable policy. */
	rememberable: boolean,
	/**  True while an exact durable remember-decision transaction is pending. */
	processing: boolean,
};

/**  Exact replacement for the one process-wide page permission surface. */
export type PagePermissionPromptView = {
	projection_revision: string,
	prompt: PagePermissionPromptEntryView | null,
};

export type ProfileKindView = "default" | "named" | "incognito";

/**
 *  Focused profile metadata. Profile isolation and lifecycle remain native
 *  authority; this view is display-only.
 */
export type ProfileView = {
	id: string,
	name: string,
	kind: ProfileKindView,
};

/**  Sanitized advisory delivered only to privileged main chrome. */
export type RuntimeSecurityAdvisory = {
	kind: RuntimeSecurityAdvisoryKind,
	update_target: RuntimeSecurityUpdateTarget,
};

/**
 *  Non-fatal, process-local classification produced before native WebView
 *  construction. Hard admission failures never reach privileged chrome.
 */
export type RuntimeSecurityAdvisoryKind = "review_overdue" | "update_recommended" | "unreviewed_runtime";

/**
 *  Fixed destination of the recommended maintenance action. No page or
 *  network response can select this value.
 */
export type RuntimeSecurityUpdateTarget = "zephium" | "operating_system" | "browser_runtime";

/**
 *  Process-local browser-runtime status. Once `restart_required` becomes true
 *  it remains true until the whole application exits; recoverable bounded
 *  user-content degradation is projected independently in the same snapshot.
 */
export type RuntimeStatus = {
	restart_required: boolean,
	/**
	 *  Bounded fail-closed aggregate of ownership scopes whose latest native
	 *  user-content observation was not exactly applied. An impossible
	 *  over-capacity observation contributes at most one sentinel. No script,
	 *  extension, profile, or native failure identity crosses this privileged
	 *  projection.
	 */
	user_content_degraded_scope_count: number,
	/**
	 *  Canonically ordered closed-vocabulary set. Rust emits at most five
	 *  entries and privileged chrome must replace, never append, projections.
	 */
	security_advisories: RuntimeSecurityAdvisory[],
};

export type RuntimeStatusChanged = RuntimeStatus;

export type SearchAction = { type: "ActivateTab"; id: string } | { type: "OpenUrl"; url: string } | { type: "RunCommand"; id: string };

export type SearchChanged = SearchResults;

export type SearchResult = {
	kind: string,
	title: string,
	detail: string,
	favicon: string | null,
	action: SearchAction,
};

export type SearchResults = {
	query: string,
	results: SearchResult[],
};

/**
 *  A folder carries bounded display metadata; a tab is a normalized reference
 *  into [`ItemsState::tabs`]. The node id and tab id intentionally match, but
 *  the explicit reference keeps consumers from inferring that invariant.
 */
export type SidebarNodeKindView = { type: "folder"; name: string } | { type: "tab"; tab_id: string };

/**
 *  One pre-order entry in the focused sidebar tree. Parents always precede
 *  descendants, sibling order is native aggregate order, and `parent_id` is
 *  `None` only for a section root.
 */
export type SidebarNodeView = {
	id: string,
	parent_id: string | null,
	section: SidebarSectionView,
	kind: SidebarNodeKindView,
};

/**
 *  Stable display section for a sidebar node. Children inherit their
 *  authoritative placement from the native item aggregate.
 */
export type SidebarSectionView = "favorites" | "pinned" | "today";

/**  One ordered space owned by the focused profile. */
export type SpaceView = {
	id: string,
	name: string,
};

/**
 *  The one retained split group owned by the focused window. Members are
 *  normalized references into [`ItemsState::tabs`] in native pane traversal
 *  order; geometry and mutable divider ratios remain native-only authority.
 */
export type SplitGroupView = {
	members: string[],
};

export type TabChanged = TabView;

export type TabView = {
	id: string,
	/**
	 *  Process-local monotonically increasing projection revision, encoded as
	 *  fixed-width hexadecimal so JavaScript can compare it without losing
	 *  integer precision. Privileged chrome rejects an older per-tab delta
	 *  after a newer presentation barrier has applied.
	 */
	projection_revision: string,
	title: string,
	url: string | null,
	loading: boolean,
	can_go_back: boolean,
	can_go_forward: boolean,
	favicon: string | null,
};

export type UiCommand = string;

export type UiInfo = {
	material: boolean,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

