// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	tabsBootstrap: () => __TAURI_INVOKE<void>("tabs_bootstrap"),
	tabsOpen: () => __TAURI_INVOKE<void>("tabs_open"),
	tabsActivate: (id: string) => __TAURI_INVOKE<void>("tabs_activate", { id }),
	tabsClose: (id: string) => __TAURI_INVOKE<void>("tabs_close", { id }),
	tabsNavigate: (id: string, input: string) => __TAURI_INVOKE<void>("tabs_navigate", { id, input }),
	tabsReload: (id: string) => __TAURI_INVOKE<void>("tabs_reload", { id }),
	tabsBack: (id: string) => __TAURI_INVOKE<void>("tabs_back", { id }),
	tabsForward: (id: string) => __TAURI_INVOKE<void>("tabs_forward", { id }),
	tabsSplit: (other: string) => __TAURI_INVOKE<void>("tabs_split", { other }),
	tabsUnsplit: () => __TAURI_INVOKE<void>("tabs_unsplit"),
	sidebarSetWidth: (width: number | null) => __TAURI_INVOKE<void>("sidebar_set_width", { width }),
	tabDragOver: (x: number | null, y: number | null) => __TAURI_INVOKE<void>("tab_drag_over", { x, y }),
	tabDrop: (id: string, x: number | null, y: number | null) => __TAURI_INVOKE<void>("tab_drop", { id, x, y }),
};

/** Events */
export const events = {
	itemsChanged: makeEvent<ItemsChanged>("items-changed"),
	tabChanged: makeEvent<TabChanged>("tab-changed"),
	uiCommand: makeEvent<UiCommand>("ui-command"),
};

/* Types */
export type ItemsChanged = ItemsState;

export type ItemsState = {
	tabs: TabView[],
	active: string | null,
};

export type TabChanged = TabView;

export type TabView = {
	id: string,
	title: string,
	url: string | null,
	loading: boolean,
	can_go_back: boolean,
	can_go_forward: boolean,
};

export type UiCommand = string;

/* Tauri Specta runtime */
type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

