// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	tabsBootstrap: () => __TAURI_INVOKE<void>("tabs_bootstrap"),
	tabsOpen: () => __TAURI_INVOKE<void>("tabs_open"),
	tabsActivate: (id: string) => __TAURI_INVOKE<void>("tabs_activate", { id }),
	tabsClose: (id: string) => __TAURI_INVOKE<void>("tabs_close", { id }),
	tabsNavigate: (id: string, input: string) => __TAURI_INVOKE<void>("tabs_navigate", { id, input }),
	tabsReload: (id: string) => __TAURI_INVOKE<void>("tabs_reload", { id }),
	tabsBack: (id: string) => __TAURI_INVOKE<void>("tabs_back", { id }),
	tabsForward: (id: string) => __TAURI_INVOKE<void>("tabs_forward", { id }),
	tabsSplit: (other: string) => __TAURI_INVOKE<void>("tabs_split", { other }),
	tabsUnsplit: () => __TAURI_INVOKE<void>("tabs_unsplit"),
	runCommand: (id: string) => __TAURI_INVOKE<void>("run_command", { id }),
	panelHide: () => __TAURI_INVOKE<void>("panel_hide"),
	settingGet: (key: string) => __TAURI_INVOKE<string | null>("setting_get", { key }),
	settingSet: (key: string, value: string) => __TAURI_INVOKE<void>("setting_set", { key, value }),
	uiInfo: () => __TAURI_INVOKE<UiInfo>("ui_info"),
	menuPopup: () => __TAURI_INVOKE<void>("menu_popup"),
	launcherSearch: (query: string) => __TAURI_INVOKE<void>("launcher_search", { query }),
	launcherRun: (action: SearchAction) => __TAURI_INVOKE<void>("launcher_run", { action }),
	sidebarSetWidth: (width: number | null) => __TAURI_INVOKE<void>("sidebar_set_width", { width }),
	tabDragOver: (x: number | null, y: number | null) => __TAURI_INVOKE<void>("tab_drag_over", { x, y }),
	tabDrop: (id: string, x: number | null, y: number | null) => __TAURI_INVOKE<void>("tab_drop", { id, x, y }),
	dividerGrab: (x: number | null, y: number | null) => __TAURI_INVOKE<void>("divider_grab", { x, y }),
	dividerDrag: (x: number | null, y: number | null) => __TAURI_INVOKE<void>("divider_drag", { x, y }),
	dividerRelease: () => __TAURI_INVOKE<void>("divider_release"),
};

/** Events */
export const events = {
	itemsChanged: makeEvent<ItemsChanged>("items-changed"),
	layoutChanged: makeEvent<LayoutChanged>("layout-changed"),
	searchChanged: makeEvent<SearchChanged>("search-changed"),
	tabChanged: makeEvent<TabChanged>("tab-changed"),
	uiCommand: makeEvent<UiCommand>("ui-command"),
};

/* Types */
/**
 *  Split divider hit-strip in window logical coordinates; the chrome renders
 *  these as drag targets on platforms without native stage dividers.
 */
export type DividerView = {
	x: number | null,
	y: number | null,
	width: number | null,
	height: number | null,
	vertical: boolean,
};

export type ItemsChanged = ItemsState;

export type ItemsState = {
	tabs: TabView[],
	active: string | null,
};

export type LayoutChanged = LayoutState;

export type LayoutState = {
	dividers: DividerView[],
};

export type SearchAction = { type: "ActivateTab"; id: string } | { type: "OpenUrl"; url: string } | { type: "RunCommand"; id: string };

export type SearchChanged = SearchResults;

export type SearchResult = {
	kind: string,
	title: string,
	detail: string,
	favicon: string | null,
	action: SearchAction,
};

export type SearchResults = {
	query: string,
	results: SearchResult[],
};

export type TabChanged = TabView;

export type TabView = {
	id: string,
	title: string,
	url: string | null,
	loading: boolean,
	can_go_back: boolean,
	can_go_forward: boolean,
	favicon: string | null,
};

export type UiCommand = string;

export type UiInfo = {
	material: boolean,
};

/* Tauri Specta runtime */
type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

