[package]
name = "zephium-ipc"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
zephium-core = { workspace = true, features = ["ipc-types"] }
serde.workspace = true
specta.workspace = true

[dev-dependencies]
serde_json.workspace = true
specta-typescript.workspace = true
specta-serde = "0.0.12"
