[package]
name = "zephium-app"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
zephium-core.workspace = true
zephium-ipc.workspace = true
url.workspace = true

[lints.rust]
unexpected_cfgs = { level = "deny", check-cfg = [
    "cfg(zephium_internal_repository_e2e)",
] }
