[package]
name = "zephium-extension-distribution"
version.workspace = true
edition.workspace = true
license.workspace = true

[features]
staging-extension-catalog = ["zephium-extension-authority/staging-extension-catalog"]
local-extension-lab = ["zephium-extension-authority/local-extension-lab"]

[dependencies]
sha2 = "=0.10.9"
thiserror.workspace = true
url.workspace = true
zephium-core.workspace = true
zephium-extension-authority.workspace = true
zephium-extension-package = { path = "../zephium-extension-package", version = "=0.1.0" }
zephium-update-transport.workspace = true
tokio = { workspace = true, features = ["sync", "time"] }

[dev-dependencies]
ring.workspace = true
