/**
 * Well-known products and services and the host whose icon stands for them,
 * so a part the model named without a vendor still shows its mark. Closed:
 * a name missing here keeps its kind's glyph.
 */
const VENDORS: Record<string, readonly string[]> = {
  "redis.io": ["Redis", "Valkey"],
  "postgresql.org": ["PostgreSQL", "Postgres"],
  "mysql.com": ["MySQL"],
  "mongodb.com": ["MongoDB", "Mongo"],
  "aws.amazon.com": [
    "AWS",
    "Amazon Web Services",
    "S3",
    "EC2",
    "Lambda",
    "AWS Lambda",
    "DynamoDB",
    "SQS",
    "SNS",
    "RDS",
    "CloudFront",
    "Aurora",
  ],
  "cloud.google.com": ["Google Cloud", "GCP", "BigQuery", "Cloud Run", "Pub/Sub"],
  "azure.microsoft.com": ["Azure", "Microsoft Azure"],
  "nodejs.org": ["Node.js", "NodeJS", "Node"],
  "react.dev": ["React", "React Native"],
  "nextjs.org": ["Next.js", "NextJS"],
  "svelte.dev": ["Svelte", "SvelteKit"],
  "vuejs.org": ["Vue", "Vue.js", "Nuxt"],
  "angular.dev": ["Angular"],
  "djangoproject.com": ["Django"],
  "rubyonrails.org": ["Ruby on Rails", "Rails"],
  "laravel.com": ["Laravel"],
  "spring.io": ["Spring Boot", "Spring"],
  "kafka.apache.org": ["Kafka", "Apache Kafka"],
  "rabbitmq.com": ["RabbitMQ"],
  "nginx.org": ["Nginx"],
  "cloudflare.com": ["Cloudflare", "Cloudflare Workers", "R2"],
  "vercel.com": ["Vercel"],
  "netlify.com": ["Netlify"],
  "stripe.com": ["Stripe"],
  "twilio.com": ["Twilio"],
  "sendgrid.com": ["SendGrid"],
  "auth0.com": ["Auth0"],
  "okta.com": ["Okta"],
  "elastic.co": ["Elasticsearch", "Elastic", "Kibana", "Logstash"],
  "kubernetes.io": ["Kubernetes", "K8s"],
  "docker.com": ["Docker"],
  "terraform.io": ["Terraform"],
  "github.com": ["GitHub", "GitHub Actions"],
  "gitlab.com": ["GitLab"],
  "sentry.io": ["Sentry"],
  "datadoghq.com": ["Datadog"],
  "grafana.com": ["Grafana", "Loki"],
  "prometheus.io": ["Prometheus"],
  "openai.com": ["OpenAI", "ChatGPT"],
  "anthropic.com": ["Anthropic", "Claude"],
  "perplexity.ai": ["Perplexity", "Perplexity Comet"],
  "arc.net": ["Arc Browser"],
  "diabrowser.com": ["Dia Browser"],
  "brave.com": ["Brave"],
  "opera.com": ["Opera", "Opera Neon"],
  "huggingface.co": ["Hugging Face", "HuggingFace"],
  "supabase.com": ["Supabase"],
  "firebase.google.com": ["Firebase", "Firestore"],
  "planetscale.com": ["PlanetScale"],
  "neon.tech": ["Neon"],
  "snowflake.com": ["Snowflake"],
  "sqlite.org": ["SQLite"],
  "rust-lang.org": ["Rust"],
  "python.org": ["Python", "CPython"],
  "go.dev": ["Go", "Golang"],
  "typescriptlang.org": ["TypeScript"],
  "deno.com": ["Deno"],
  "bun.sh": ["Bun"],
  "tauri.app": ["Tauri"],
  "electronjs.org": ["Electron"],
  "flutter.dev": ["Flutter"],
  "swift.org": ["Swift"],
  "kotlinlang.org": ["Kotlin"],
  "java.com": ["Java"],
  "dotnet.microsoft.com": [".NET", "ASP.NET"],
  "php.net": ["PHP"],
  "graphql.org": ["GraphQL"],
  "apollographql.com": ["Apollo", "Apollo Server", "Apollo Client"],
  "prisma.io": ["Prisma"],
  "hasura.io": ["Hasura"],
  "clickhouse.com": ["ClickHouse"],
  "cassandra.apache.org": ["Cassandra", "Apache Cassandra"],
  "memcached.org": ["Memcached"],
  "minio.io": ["MinIO"],
  "backblaze.com": ["Backblaze", "Backblaze B2"],
  "digitalocean.com": ["DigitalOcean"],
  "hetzner.com": ["Hetzner"],
  "fly.io": ["Fly.io"],
  "render.com": ["Render"],
  "railway.app": ["Railway"],
  "heroku.com": ["Heroku"],
  "linode.com": ["Linode", "Akamai Cloud"],
  "ovhcloud.com": ["OVHcloud", "OVH"],
  "algolia.com": ["Algolia"],
  "meilisearch.com": ["Meilisearch"],
  "mapbox.com": ["Mapbox"],
  "segment.com": ["Segment"],
  "mixpanel.com": ["Mixpanel"],
  "amplitude.com": ["Amplitude"],
  "posthog.com": ["PostHog"],
  "resend.com": ["Resend"],
  "postmarkapp.com": ["Postmark"],
  "mailgun.com": ["Mailgun"],
  "slack.com": ["Slack"],
  "discord.com": ["Discord"],
  "notion.so": ["Notion"],
  "figma.com": ["Figma"],
  "linear.app": ["Linear"],
  "fastapi.tiangolo.com": ["FastAPI"],
  "flask.palletsprojects.com": ["Flask"],
  "expressjs.com": ["Express", "Express.js"],
  "nestjs.com": ["NestJS"],
  "fastify.dev": ["Fastify"],
  "hono.dev": ["Hono"],
  "remix.run": ["Remix"],
  "astro.build": ["Astro"],
  "vite.dev": ["Vite"],
  "tailwindcss.com": ["Tailwind", "Tailwind CSS"],
  "expo.dev": ["Expo"],
  "upstash.com": ["Upstash"],
  "clerk.com": ["Clerk"],
  "workos.com": ["WorkOS"],
  "keycloak.org": ["Keycloak"],
  "temporal.io": ["Temporal"],
  "celeryq.dev": ["Celery"],
  "sidekiq.org": ["Sidekiq"],
  "bullmq.io": ["BullMQ"],
  "inngest.com": ["Inngest"],
  "trigger.dev": ["Trigger.dev"],
  "airflow.apache.org": ["Airflow", "Apache Airflow"],
  "dagster.io": ["Dagster"],
  "prefect.io": ["Prefect"],
  "nats.io": ["NATS"],
  "pulsar.apache.org": ["Pulsar", "Apache Pulsar"],
  "redpanda.com": ["Redpanda"],
  "traefik.io": ["Traefik"],
  "envoyproxy.io": ["Envoy"],
  "istio.io": ["Istio"],
  "konghq.com": ["Kong"],
  "haproxy.org": ["HAProxy"],
  "caddyserver.com": ["Caddy"],
  "vaultproject.io": ["Vault", "HashiCorp Vault"],
  "consul.io": ["Consul"],
  "pulumi.com": ["Pulumi"],
  "opentelemetry.io": ["OpenTelemetry", "OTel"],
  "honeycomb.io": ["Honeycomb"],
  "newrelic.com": ["New Relic"],
  "pagerduty.com": ["PagerDuty"],
  "fastly.com": ["Fastly"],
  "akamai.com": ["Akamai"],
  "openrouter.ai": ["OpenRouter"],
  "cohere.com": ["Cohere"],
  "mistral.ai": ["Mistral", "Mistral AI"],
  "gemini.google.com": ["Gemini", "Google Gemini"],
  "groq.com": ["Groq"],
  "together.ai": ["Together AI"],
  "fireworks.ai": ["Fireworks AI"],
  "replicate.com": ["Replicate"],
  "modal.com": ["Modal"],
  "ollama.com": ["Ollama"],
  "vllm.ai": ["vLLM"],
  "ray.io": ["Ray"],
  "pinecone.io": ["Pinecone"],
  "weaviate.io": ["Weaviate"],
  "qdrant.tech": ["Qdrant"],
  "milvus.io": ["Milvus"],
  "trychroma.com": ["Chroma", "ChromaDB"],
  "langchain.com": ["LangChain", "LangGraph", "LangSmith"],
  "llamaindex.ai": ["LlamaIndex"],
  "wandb.ai": ["Weights & Biases", "W&B"],
  "mlflow.org": ["MLflow"],
  "pytorch.org": ["PyTorch"],
  "tensorflow.org": ["TensorFlow"],
  "jupyter.org": ["Jupyter"],
  "numpy.org": ["NumPy"],
  "pandas.pydata.org": ["pandas"],
  "streamlit.io": ["Streamlit"],
  "gradio.app": ["Gradio"],
  "scylladb.com": ["ScyllaDB"],
  "cockroachlabs.com": ["CockroachDB"],
  "neo4j.com": ["Neo4j"],
  "duckdb.org": ["DuckDB"],
  "timescale.com": ["TimescaleDB", "Timescale"],
  "influxdata.com": ["InfluxDB"],
  "turso.tech": ["Turso"],
  "convex.dev": ["Convex"],
  "appwrite.io": ["Appwrite"],
  "pocketbase.io": ["PocketBase"],
  "turbo.build": ["Turborepo"],
  "pnpm.io": ["pnpm"],
  "npmjs.com": ["npm"],
  "yarnpkg.com": ["Yarn"],
  "webpack.js.org": ["Webpack"],
  "vitest.dev": ["Vitest"],
  "jestjs.io": ["Jest"],
  "playwright.dev": ["Playwright"],
  "cypress.io": ["Cypress"],
  "eslint.org": ["ESLint"],
  "prettier.io": ["Prettier"],
  "jira.atlassian.com": ["Jira"],
};

/** Names that are also plain words count only as a part's whole name. */
const PLAIN = new Set([
  "go",
  "swift",
  "spring",
  "rails",
  "render",
  "railway",
  "linear",
  "segment",
  "neon",
  "bun",
  "elastic",
  "apollo",
  "snowflake",
  "notion",
  "slack",
  "resend",
  "amplitude",
  "aurora",
  "loki",
  "node",
  "express",
  "flask",
  "remix",
  "astro",
  "temporal",
  "prefect",
  "envoy",
  "kong",
  "caddy",
  "vault",
  "consul",
  "modal",
  "ray",
  "replicate",
  "chroma",
  "convex",
  "pulsar",
  "honeycomb",
  "yarn",
  "jest",
  "mistral",
]);
/** Names a note uses in passing ("react to", "a lambda") count only in a part's name. */
const NAMED = new Set(["react", "lambda", "electron", "stripe", "claude"]);

const HOSTS = new Map<string, string>();
for (const [host, names] of Object.entries(VENDORS))
  for (const name of names) HOSTS.set(name.toLowerCase(), host);
const escape = (text: string) => text.replace(/[.*+?^${}()|[\]\\/]/gu, "\\$&");
// Whole words, longest first, so "Apache Kafka" wins over "Kafka" where both would match.
const words = (skip: (name: string) => boolean) =>
  new RegExp(
    `(?<![\\p{L}\\p{N}])(${[...HOSTS.keys()]
      .filter((name) => !skip(name))
      .sort((a, b) => b.length - a.length)
      .map(escape)
      .join("|")})(?![\\p{L}\\p{N}])`,
    "iu",
  );
const IN_NAME = words((name) => PLAIN.has(name));
const IN_NOTE = words((name) => PLAIN.has(name) || NAMED.has(name));

/** The host a part's name or note names, or none. */
function named(text: string, name: boolean): string | null {
  const value = text.trim().toLowerCase();
  if (!value) return null;
  if (name && PLAIN.has(value)) return HOSTS.get(value) ?? null;
  const match = (name ? IN_NAME : IN_NOTE).exec(value);
  return match ? (HOSTS.get(match[1]!) ?? null) : null;
}

/** The words that name a host's maker: its products here, and its own name ("amazon"). */
function brand(host: string): string[] {
  const labels = host.split(".");
  const own = labels.length >= 2 ? labels[labels.length - 2]! : host;
  return [own, ...(VENDORS[host] ?? []).map((name) => name.toLowerCase())];
}
const mentions = (text: string, word: string) =>
  new RegExp(`(?<![\\p{L}\\p{N}])${escape(word)}(?![\\p{L}\\p{N}])`, "iu").test(text);

/**
 * The host whose mark a part shows, only when the part is that maker's product:
 * a stated vendor its name or note names ("Amazon Cognito" on aws.amazon.com),
 * else a well-known product its name, then its note, names as a whole word.
 * A part merely run on a platform ("API service" on AWS) shows no mark.
 */
export function vendorHost(vendor: string | undefined, name: string, note = ""): string | null {
  const stated = vendor?.trim().toLowerCase();
  if (stated && brand(stated).some((word) => mentions(`${name} ${note}`, word))) return stated;
  return named(name, true) ?? named(note, false);
}
