[package]
name = "zephium-blocker-service"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
flate2 = "=1.1.9"
serde.workspace = true
serde_json.workspace = true
sha2 = "=0.10.9"
thiserror.workspace = true
zephium-blocker.workspace = true
zephium-blocker-update.workspace = true
zephium-core.workspace = true

[dev-dependencies]
tempfile.workspace = true
