[package]
name = "zephium-extension-service"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
zephium-core.workspace = true
zephium-extension-repository.workspace = true
zephium-private-fs.workspace = true
zephium-store.workspace = true

[dev-dependencies]
tempfile.workspace = true
