[package]
name = "zephium-engine"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
zephium-core.workspace = true
wry.workspace = true
serde_json.workspace = true
url.workspace = true

[dev-dependencies]
tempfile.workspace = true

[target.'cfg(target_os = "windows")'.dependencies]
raw-window-handle.workspace = true
webview2-com = "0.38"
windows = { version = "0.61", features = [
    "Win32_Foundation",
    "Win32_Graphics_Gdi",
    "Win32_System_LibraryLoader",
    "Win32_System_Threading",
    "Win32_UI_HiDpi",
    "Win32_UI_Input_KeyboardAndMouse",
    "Win32_UI_WindowsAndMessaging",
] }
windows-core = "0.61"

[target.'cfg(all(unix, not(target_os = "macos")))'.dependencies]
gtk = "0.18"
webkit2gtk = { version = "=2.0.2", features = ["v2_40"] }

[target.'cfg(target_os = "macos")'.dependencies]
block2 = "0.6"
dispatch2 = { version = "0.3.1", default-features = false, features = ["std"] }
objc2 = "0.6"
objc2-app-kit = "0.3"
objc2-core-graphics = "0.3"
objc2-foundation = "0.3"
objc2-web-kit = "0.3"
objc2-quartz-core = "0.3"
raw-window-handle.workspace = true
