[package]
name = "zephium-engine"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
zephium-core.workspace = true
wry.workspace = true
raw-window-handle.workspace = true

[target.'cfg(target_os = "macos")'.dependencies]
objc2 = "0.6"
objc2-app-kit = "0.3"
objc2-core-graphics = "0.3"
objc2-foundation = "0.3"
objc2-web-kit = "0.3"
objc2-quartz-core = "0.3"
