// This file has been generated by Specta. Do not edit this file manually.
export type ProfileId = string;

export type WorkActivityV1 = "planning" | "delegating" | "reading" | "comparing" | "producing_artifact" | "waiting_for_approval" | "waiting_for_human" | "cancelling" | "finishing";

export type WorkApprovalRequestV1 = {
	version: number,
	work: WorkId,
	expected_revision: WorkRevision,
	limits: WorkExecutionLimits,
	scope: WorkBrowseScope,
	primary: WorkPlanNodeId | null,
};

export type WorkArtifactDataV1 = { kind: "document"; paragraphs: string[] } | { kind: "table"; columns: string[]; rows: string[][] } | { kind: "comparison"; criteria: string[]; alternatives: WorkComparisonAlternative[] } |
/**  Decimal strings preserve values independently of renderer floating point. */
{ kind: "chart"; x_label: string; y_label: string; series: WorkChartSeries[] } | { kind: "checklist"; items: WorkChecklistItem[] } | { kind: "evidence_collection"; summary: string } |
/**  A descriptive card, not an interactive native context or navigation grant. */
{ kind: "browser_resource_preview"; title: string; url: string; summary: string };

export type WorkArtifactDecision = "accepted" | "rejected";

/** Immutable semantic artifact identity. */
export type WorkArtifactId = string;

export type WorkArtifactPresentationV1 = "automatic" | "compact" | "expanded";

export type WorkArtifactUserState = {
	artifact: WorkArtifactId,
	revision: WorkRevision,
	decision: WorkArtifactDecision | null,
	edited_data: WorkArtifactDataV1 | null,
	/**  Citations for edited content. Original citations remain on the artifact. */
	evidence: WorkEvidenceLink[],
};

export type WorkArtifactV1 = {
	version: number,
	id: WorkArtifactId,
	execution: WorkExecutionId,
	node: WorkPlanNodeId,
	attempt: WorkAttemptId,
	output: string,
	title: string,
	data: WorkArtifactDataV1,
	evidence: WorkEvidenceLink[],
	review: WorkOutputReview,
	presentation: WorkArtifactPresentationV1,
};

export type WorkAttemptFact = {
	id: WorkAttemptId,
	node: WorkPlanNodeId,
	status: WorkAttemptStatus,
	/**
	 *  Reservation is retained for unknown outcomes. Settled accounting names
	 *  exact usage or a conservative ceiling; missing means unknown, never zero.
	 */
	usage: WorkUsage | null,
};

/** Exact durable worker attempt identity. */
export type WorkAttemptId = string;

export type WorkAttemptStatus = "running" | "succeeded" | "failed" | "cancelled" | "outcome_unknown";

/**
 *  Attribution is descriptive history, never authorization. Legacy content has
 *  unknown attribution; application callers cannot impersonate agent authors.
 */
export type WorkAuthor = "user" | "primary_agent" | "other_agent" | "legacy_unknown";

/**
 *  The command ID is profile-scoped and survives lost replies and restart.
 *  New Work, question and plan identities are minted by Rust exactly once.
 */
export type WorkAuthoringCommandV1 = {
	version: number,
	command: WorkCommandId,
	intent: WorkAuthoringIntent,
};

export type WorkAuthoringIntent = { kind: "create"; objective: string } | { kind: "edit"; work: WorkId; expected_revision: WorkRevision; edit: WorkUserEdit } | { kind: "delete"; work: WorkId; expected_revision: WorkRevision };

export type WorkAuthoringReceipt = {
	command: WorkCommandId,
	work: WorkId,
	applied_revision: WorkRevision,
	deleted: boolean,
};

export type WorkAuthoringStatus = "draft" | "needs_input" | "plan_ready";

export type WorkBrowseRoute = {
	origin: string,
	path_prefix: string,
};

export type WorkBrowseScope = {
	start_url: string,
	/**
	 *  Exact HTTPS origins and path prefixes, interpreted by the browser
	 *  discovery compiler. Redirects do not implicitly extend this set.
	 */
	routes: WorkBrowseRoute[],
	max_hops: number,
};

export type WorkCapability = { kind: "public_browse"; scope: WorkBrowseScope } |
/**
 *  A primary agent may assign pre-approved children within this envelope
 *  and synthesize their results. This is not a direct browser/action port.
 */
{ kind: "coordinate"; scope: WorkBrowseScope } |
/**  Structured handoffs from completed plan dependencies only. */
{ kind: "synthesize" };

export type WorkChartPoint = {
	label: string,
	value: string,
};

export type WorkChartSeries = {
	name: string,
	points: WorkChartPoint[],
};

export type WorkChecklistItem = {
	text: string,
	completed: boolean,
};

/** Idempotency correlation only, never an entity capability. */
export type WorkCommandId = string;

export type WorkCommandReceipt = {
	command: WorkCommandId,
	applied_revision: WorkRevision,
	execution: WorkExecutionId,
};

/**
 *  Retry the same command and expected revision after a lost reply. The Store
 *  returns its original receipt plus current facts. Reusing an ID with changed
 *  operands is a conflict. Receipt eviction is never automatic.
 */
export type WorkCommandV1 = {
	version: number,
	work: WorkId,
	expected_revision: WorkRevision,
	command: WorkCommandId,
	intent: WorkRuntimeIntent,
};

export type WorkComparisonAlternative = {
	name: string,
	values: string[],
};

export type WorkEvidenceLink = {
	/**
	 *  Reference to a source in the original persisted extraction, never a URL
	 *  invented by an artifact-producing model.
	 */
	extraction_id: WorkArtifactId,
	source_id: number,
};

/**
 *  Selected historical source content. This cannot restore a browser context,
 *  action reference, or execution authority. It remains untrusted source data.
 */
export type WorkEvidencePreviewV1 = {
	version: number,
	link: WorkEvidenceLink,
	origin: string,
	role: string,
	text: string,
	truncated: boolean,
	/**  Decimal byte count avoids JavaScript integer precision loss. */
	source_bytes: string,
};

export type WorkExecutionFact = {
	id: WorkExecutionId,
	approved_revision: WorkRevision,
	spec: WorkExecutionSpec,
	status: WorkExecutionStatus,
	attempts: WorkAttemptFact[],
	artifacts: WorkArtifactV1[],
	/**  User edits and decisions never overwrite the original agent output. */
	user_artifacts?: WorkArtifactUserState[],
};

/** Durable execution identity, never a live admission. */
export type WorkExecutionId = string;

export type WorkExecutionLimits = {
	model_tokens: number,
	cost_micro_usd: number,
	operations: number,
	timeout_seconds: number,
	max_workers: number,
};

export type WorkExecutionSpec = {
	plan_revision: WorkRevision,
	limits: WorkExecutionLimits,
	nodes: WorkNodeExecutionSpec[],
};

export type WorkExecutionStatus = "approved" | "running" | "cancel_requested" | "completed" | "needs_review" | "cancelled" | "failed" | "interrupted";

export type WorkExpectedOutput = {
	name: string,
	description: string,
	review: WorkOutputReview,
};

export type WorkFailureV1 = "invalid" | "capacity" | "conflict" | "not_found" | "profile_unavailable" | "unavailable" | "shutdown" | "outcome_unknown";

/** Durable profile-owned Work identity; never an execution capability. */
export type WorkId = string;

export type WorkLifecycle = "active" | "archived";

export type WorkNodeExecutionSpec = {
	node: WorkPlanNodeId,
	/**
	 *  A direct delegation edge, independent from data dependencies. Its
	 *  authority must be contained in its parent's approved capability.
	 */
	parent: WorkPlanNodeId | null,
	capability: WorkCapability,
	limits: WorkExecutionLimits,
};

export type WorkNodeProposal = {
	key: number,
	objective: string,
	dependencies: number[],
	outputs: WorkExpectedOutput[],
};

/**  Requested output review level, never evidence that a requirement was met. */
export type WorkOutputReview = "mechanical" | "source_mapped_needs_review" | "user_acceptance";

export type WorkPlanDraft = {
	id: WorkPlanId,
	nodes: WorkPlanNode[],
};

/** Durable plan identity, independent of its immutable revisions. */
export type WorkPlanId = string;

export type WorkPlanNode = {
	id: WorkPlanNodeId,
	objective: string,
	dependencies: WorkPlanNodeId[],
	outputs: WorkExpectedOutput[],
};

/** Durable responsibility in a draft; not an execution lease or a Task. */
export type WorkPlanNodeId = string;

export type WorkPlanProposal = {
	nodes: WorkNodeProposal[],
};

/**
 *  One non-replayable provider operation. After a lost result, refresh Work;
 *  never automatically repeat generation or interpret missing usage as zero.
 */
export type WorkPlanRequestV1 = {
	version: number,
	work: WorkId,
	expected_revision: WorkRevision,
};

export type WorkPlanRevision = {
	author: WorkAuthor,
	revision: WorkRevision,
	/**  Exact Work context from which the proposal was accepted. */
	basis_revision: WorkRevision,
	draft: WorkPlanDraft,
};

export type WorkPlanningFailureV1 = { kind: "invalid" } | { kind: "capacity" } | { kind: "unavailable" } | { kind: "cancelled" } | { kind: "timeout" } | { kind: "stale" } | { kind: "needs_input" } | { kind: "privacy" } | { kind: "provider_outcome_unknown" } | { kind: "provider_refused" } | { kind: "store"; error: WorkFailureV1 };

export type WorkPlanningOutcomeV1 = { kind: "settled"; response: WorkResponseV1 } | { kind: "refused"; reason: WorkPlanningFailureV1 };

export type WorkPlanningResponseV1 = {
	version: number,
	profile: string,
	work: WorkId,
	basis_revision: WorkRevision,
	usage: WorkPlanningUsageV1 | null,
	outcome: WorkPlanningOutcomeV1,
};

export type WorkPlanningUsageV1 = {
	input_tokens: number,
	output_tokens: number,
	cost_ceiling_micro_usd: string,
};

export type WorkQueryKindV1 = { kind: "projection"; work: WorkId } | { kind: "list"; after: WorkId | null; limit: number } | { kind: "plan_history"; work: WorkId } | { kind: "plan"; work: WorkId; revision: WorkRevision } | { kind: "evidence"; work: WorkId; link: WorkEvidenceLink };

export type WorkQueryV1 = {
	version: number,
	query: WorkQueryKindV1,
};

export type WorkQuestion = {
	basis_revision: WorkRevision | null,
	objective_revision: WorkRevision | null,
	state: WorkQuestionState,
	author: WorkAuthor,
	answer_author: WorkAuthor | null,
	id: WorkQuestionId,
	prompt: string,
	options: string[],
	answer: string | null,
};

/** Durable clarification question identity. */
export type WorkQuestionId = string;

export type WorkQuestionState = "active" | "answered" | "superseded" | "dismissed";

export type WorkReplyV1 = { kind: "approval_draft"; work: WorkId; expected_revision: WorkRevision; spec: WorkExecutionSpec } | { kind: "projection"; projection: WorkRuntimeProjection } | { kind: "authoring_applied"; receipt: WorkAuthoringReceipt } | { kind: "execution_applied"; projection: WorkRuntimeProjection; receipt: WorkCommandReceipt } | { kind: "evidence"; evidence: WorkEvidencePreviewV1 } | { kind: "snapshot"; snapshot: WorkSnapshot } | { kind: "plan"; plan: WorkPlanRevision } | { kind: "plan_history"; revisions: WorkRevision[] } | { kind: "page"; works: WorkSummary[]; next: WorkId | null } | { kind: "error"; error: WorkFailureV1 };

/**
 *  Closed product reply grammar: the host-only RuntimeStarted reply cannot
 *  cross this conversion, so a read or JSON round trip cannot mint an attempt.
 */
export type WorkResponseV1 = {
	version: number,
	profile: string,
	reply: WorkReplyV1,
};

/**
 *  SQLite- and JavaScript-safe ordered revision. The wire representation is a
 *  decimal string, so later revisions cannot be rounded by a frontend number.
 */
export type WorkRevision = string;

/**
 *  Internal Store grammar. User commands and host-only attempt facts have
 *  separate variants at the application edge; IPC never accepts settlements.
 */
export type WorkRuntimeIntent = { kind: "review_artifact"; execution: WorkExecutionId; artifact: WorkArtifactId; decision: WorkArtifactDecision } | { kind: "edit_artifact"; execution: WorkExecutionId; artifact: WorkArtifactId; data: WorkArtifactDataV1; evidence: WorkEvidenceLink[] } | { kind: "approve"; spec: WorkExecutionSpec } | { kind: "cancel"; execution: WorkExecutionId } |
/**  Explicitly acknowledge that an old owner is gone. Cannot restart it. */
{ kind: "acknowledge_interruption"; execution: WorkExecutionId };

export type WorkRuntimeProjection = {
	version: number,
	work: WorkSnapshot,
	executions: WorkExecutionFact[],
	/**  Old incarnation has no live authority. Facts and reservations remain. */
	interrupted: WorkExecutionId[],
};

/**
 *  A stale, missed or reordered signal never changes durable execution state.
 *  Render only for the matching owner, Work and durable revision.
 */
export type WorkSignalV1 = {
	version: number,
	profile: string,
	work: WorkId,
	basis_revision: WorkRevision,
	execution: WorkExecutionId,
	node: WorkPlanNodeId,
	attempt: WorkAttemptId,
	activity: WorkActivityV1,
};

/**  Bounded full-resynchronization projection. Serialized facts grant nothing. */
export type WorkSnapshot = {
	lifecycle: WorkLifecycle,
	objective_revision: WorkRevision,
	context_revision: WorkRevision,
	objective_author: WorkAuthor,
	schema_version: number,
	id: WorkId,
	profile: ProfileId,
	revision: WorkRevision,
	objective: string,
	status: WorkAuthoringStatus,
	plan: WorkPlanRevision | null,
	questions: WorkQuestion[],
};

export type WorkStartRequestV1 = {
	version: number,
	work: WorkId,
	expected_revision: WorkRevision,
	execution: WorkExecutionId,
};

export type WorkSummary = {
	lifecycle: WorkLifecycle,
	schema_version: number,
	id: WorkId,
	revision: WorkRevision,
	status: WorkAuthoringStatus,
	objective: string,
};

export type WorkUsage = {
	model_tokens: number,
	cost_micro_usd: number,
	operations: number,
	accounting: WorkUsageAccounting,
};

export type WorkUsageAccounting = "exact" | "conservative_reservation";

export type WorkUserEdit = { kind: "set_objective"; objective: string } | { kind: "open_question"; prompt: string; options: string[] } | { kind: "answer_question"; id: WorkQuestionId; answer: string } | { kind: "dismiss_question"; id: WorkQuestionId } | { kind: "replace_draft"; proposal: WorkPlanProposal } | { kind: "archive" } | { kind: "restore" } | { kind: "compact_history" };

export type WorkProjectionV1 = WorkRuntimeProjection;
