[package]
name = "zephium-desktop"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
name = "zephium_desktop_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build.workspace = true
tauri-utils = "2"
serde_json.workspace = true
json-patch = "3"

[dependencies]
tauri.workspace = true
zephium-core.workspace = true
zephium-ipc.workspace = true
zephium-app.workspace = true
zephium-engine.workspace = true
zephium-store.workspace = true
tauri-plugin-global-shortcut.workspace = true
tauri-plugin-single-instance.workspace = true
window-vibrancy = "0.7"
serde.workspace = true
serde_json.workspace = true
specta.workspace = true
specta-typescript.workspace = true
tauri-specta.workspace = true

[target.'cfg(target_os = "windows")'.dependencies]
raw-window-handle.workspace = true
webview2-com = "0.38"
windows = { version = "0.61", features = ["Win32_Foundation", "Win32_Graphics_Dwm", "Win32_Security", "Win32_Storage_FileSystem", "Win32_System_Console", "Win32_System_Pipes"] }

[target.'cfg(all(unix, not(target_os = "macos")))'.dependencies]
gtk = "0.18"
webkit2gtk = { version = "=2.0.2", features = ["v2_40"] }

[target.'cfg(target_os = "macos")'.dependencies]
block2 = "0.6"
objc2 = "0.6"
objc2-app-kit = "0.3"
objc2-foundation = "0.3"
objc2-web-kit = "0.3"
raw-window-handle.workspace = true
